[package]
name = "payjoin-cli"
version = "0.0.1"
authors = ["Dan Gould <d@ngould.dev>", "Martin Habovstiak <martin.habovstiak@gmail.com>"]
repository = "https://github.com/payjoin/rust-payjoin"
readme = "README.md"
edition = "2021"
resolver = "2"

[[bin]]
name = "payjoin-cli"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
native-certs = ["ureq/native-certs"]
danger-local-https = ["rcgen", "rustls/dangerous_configuration", "hyper-rustls"]

[dependencies]
anyhow = "1.0.70"
bip21 = "0.3.1"
bitcoincore-rpc = "0.17.0"
clap = { version = "3.2.22", features = ["derive"] }
config = "0.13.3"
env_logger = "0.9.0"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "0.24", optional = true }
log = "0.4.7"
payjoin = { path = "../payjoin", features = ["send", "receive", "base64"] }
ureq = "2.8.0"
rcgen = { version = "0.11.1", optional = true }
rustls = { version = "0.21.9", optional = true }
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.12.0", features = ["full"] }
url = "2.2.1"

[dev-dependencies]
bitcoind = { version = "0.31.1", features = ["0_21_2"] }
