[package]
name = "payjoin-test-utils"
version = "0.0.1"
edition = "2021"
authors = ["Dan Gould <d@ngould.dev>"]
description = "Payjoin test utilities"
repository = "https://github.com/payjoin/rust-payjoin"
rust-version = "1.85"
license = "MIT"

[dependencies]
bitcoin = { version = "0.32.5", features = ["base64"] }
bitcoincore-rpc = "0.19.0"
bitcoind = { version = "0.36.0", features = ["0_21_2"] }
http = "1.1.0"
log = "0.4.7"
ohttp = { package = "bitcoin-ohttp", version = "0.6.0" }
ohttp-relay = { version = "0.0.10", features = ["_test-util"] }
once_cell = "1.19.0"
payjoin = { version = "0.24.0", features = ["io", "_danger-local-https", "_test-utils"] }
payjoin-directory = { version = "0.0.3", features = ["_danger-local-https"] }
rcgen = "0.11"
rustls = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
testcontainers = "0.15.0"
testcontainers-modules = { version = "0.3.7", features = ["redis"] }
tokio = { version = "1.38.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.2.2"
