[package]
name = "payjoin-test-utils"
version = "0.0.1"
edition = "2021"
authors = ["Dan Gould <d@ngould.dev>"]
description = "Payjoin test utilities"
repository = "https://github.com/payjoin/rust-payjoin"
rust-version = "1.85"
license = "MIT"

[dependencies]
bitcoin = { version = "0.32.7", features = ["base64"] }
bitcoincore-rpc = "0.19.0"
bitcoind = { version = "0.36.1", features = ["0_21_2"] }
http = "1.3.1"
log = "0.4.27"
ohttp = { package = "bitcoin-ohttp", version = "0.6.0" }
ohttp-relay = { version = "0.0.11", features = ["_test-util"] }
once_cell = "1.21.3"
payjoin = { version = "0.24.0", features = ["io", "_manual-tls", "_test-utils"] }
payjoin-directory = { version = "0.0.3", features = ["_manual-tls"] }
rcgen = "0.14.3"
rustls = { version = "0.23.31", default-features=false, features = ["ring"] }
reqwest = { version = "0.12.23", default-features = false, features = ["rustls-tls"] }
testcontainers-modules = { version = "0.12.1", features = ["redis"]}
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = "2.5.4"
