[package]
name = "payjoin-ffi"
version = "0.23.0"
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = ["tests"]

[features]
_test-utils = ["payjoin-test-utils", "tokio", "bitcoind"]
uniffi = ["uniffi/cli", "bitcoin-ffi/default"]
pki-https = []

[lib]
name = "payjoin_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[build-dependencies]
uniffi = { version = "0.29.1", features = ["build"] }

[dependencies]
base64 = "0.22.1"
bitcoind = { version = "0.36.0", features = ["0_21_2"], optional = true }
bitcoin-ffi = { git = "https://github.com/benalleng/bitcoin-ffi.git", rev = "8e3a23b" }
hex = "0.4.3"
lazy_static = "1.5.0"
ohttp = { package = "bitcoin-ohttp", version = "0.6.0" }
payjoin = { version = "0.23.0", features = ["v1", "v2", "io", "pki-https"] }
payjoin-test-utils = { version = "0.0.0", optional = true }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.58"
tokio = { version = "1.38.0", features = ["full"], optional = true }
uniffi = { version = "0.29.1", optional = true }
url = "2.5.0"

[dev-dependencies]
bdk = { version = "0.29.0", features = ["all-keys", "use-esplora-ureq", "keys-bip39", "rpc"] }
bitcoincore-rpc = "0.19.0"
http = "1"
ohttp-relay = "0.0.8"
rcgen = { version = "0.11" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
rustls = "0.22.2"
testcontainers = "0.15.0"
testcontainers-modules = { version = "0.1.3", features = ["redis"] }
uniffi = { version = "0.29.1", features = ["bindgen-tests"] }

[profile.release-smaller]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
strip = true

[patch.crates-io.payjoin]
path = "../payjoin"

[patch.crates-io.payjoin-test-utils]
path = "../payjoin-test-utils"
