[package]
name = "payjoin-ffi"
version = "0.24.0"
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = ["tests"]

[features]
default = ["io"]
dart = ["dep:uniffi-dart"]
io = ["payjoin/io"]
_test-utils = ["payjoin-test-utils", "tokio", "io"]
_manual-tls = ["payjoin/_manual-tls"]
wasm_js = ["getrandom/js"]

[lib]
name = "payjoin_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[build-dependencies]
uniffi-dart = { git = "https://github.com/Uniffi-Dart/uniffi-dart.git", rev = "364b117", features = ["build"], optional = true }
uniffi = { version = "0.30.0", features = ["build", "cli"] }

[dependencies]
base64 = "0.22.1"
bitcoin-ffi = { git = "https://github.com/bitcoindevkit/bitcoin-ffi", rev = "39cc12b" }
getrandom = "0.2"
hex = "0.4.3"
lazy_static = "1.5.0"
ohttp = { package = "bitcoin-ohttp", version = "0.6.0" }
payjoin = { version = "1.0.0-rc.1", features = ["v1", "v2"] }
payjoin-test-utils = { version = "0.0.1", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
thiserror = "2.0.14"
tokio = { version = "1.47.1", features = ["full"], optional = true }
uniffi-dart = { git = "https://github.com/Uniffi-Dart/uniffi-dart.git", rev = "364b117", optional = true }
uniffi = { version = "0.30.0" }
url = "2.5.4"

[dev-dependencies]
bdk = { version = "0.29.0", features = ["all-keys", "use-esplora-ureq", "keys-bip39", "rpc"] }
