[package]
name = "payjoin-ffi"
version = "0.24.0"
edition = "2021"
license = "MIT OR Apache-2.0"
exclude = ["tests"]

[features]
_test-utils = ["payjoin-test-utils", "tokio", "bitcoind"]
_manual-tls = ["payjoin/_manual-tls"]

[lib]
name = "payjoin_ffi"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[build-dependencies]
uniffi = { version = "0.29.1", features = ["build", "cli"] }
uniffi-dart = { git = "https://github.com/Uniffi-Dart/uniffi-dart.git", rev = "b6186bc", features = ["build"] }

[dependencies]
base64 = "0.22.1"
bitcoind = { version = "0.36.0", features = ["0_21_2"], optional = true }
bitcoin-ffi = { git = "https://github.com/benalleng/bitcoin-ffi.git", rev = "8e3a23b" }
hex = "0.4.3"
lazy_static = "1.5.0"
ohttp = { package = "bitcoin-ohttp", version = "0.6.0" }
payjoin = { version = "0.24.0", features = ["v1", "v2", "io"] }
payjoin-test-utils = { version = "0.0.1", optional = true }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.58"
tokio = { version = "1.38.0", features = ["full"], optional = true }
uniffi = { version = "0.29.1" }
uniffi-dart = { git = "https://github.com/Uniffi-Dart/uniffi-dart.git", rev = "b6186bc" }
url = "2.5.0"

[dev-dependencies]
bdk = { version = "0.29.0", features = ["all-keys", "use-esplora-ureq", "keys-bip39", "rpc"] }
bitcoincore-rpc = "0.19.0"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
strip = true

[patch.crates-io]
payjoin = { path = "../payjoin" }
payjoin-test-utils = { path = "../payjoin-test-utils" }
payjoin-directory = { path = "../payjoin-directory" }
