[bindings.kotlin]
package_name = "org.payjoindevkit"
cdylib_name = "payjoin_ffi"

[bindings.python]
cdylib_name = "payjoin_ffi"

[bindings.swift]
cdylib_name = "payjoin_ffi"

[bindings.dart]
cdylib_name = "payjoin_ffi"
package_name = "payjoin"
