[package]
name = "noiseexplorer_nnpsk0"
version = "1.0.3"
authors = ["Symbolic Software <georgio@symbolic.software>"]
edition = "2018"

[dependencies]
blake2-rfc = "0.2.18"
constant_time_eq = "0.1.5"
hacl-star = "0.1.0"
hex = "0.4.3"
rand = "0.6.5"
zeroize = "1.3.0"