[package]
name = "payjoin"
version = "0.3.0-alpha"
authors = ["Dan Gould <dan@chaincase.app>"]
description = "PayJoin Library for the BIP78 Pay to Endpoint protocol."
homepage = "https://github.com/chaincase-app/payjoin"
repository = "https://github.com/chaincase-app/payjoin"
readme = "README.md"
keywords = ["bip78", "payjoin", "bitcoin"]
categories = ["api-bindings", "cryptography::cryptocurrencies", "network-programming"]
license = "MITNFA"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
sender = []
receiver = ["rand"]

[dependencies]
bitcoin = "0.27.1"
base64 = "0.13.0"
rand = { version = "0.8.4", optional = true }
bip21 = "0.1.1"
url = "2.2.2"

[dev-dependencies]
bitcoind = { version = "0.27.1", features = ["0_21_1"] }
env_logger = "0.9.0"
log = "0.4.14"

[package.metadata.docs.rs]
features = ["sender"]