[package]
name = "payjoin"
version = "0.13.0"
authors = ["Dan Gould <d@ngould.dev>"]
description = "Payjoin Library for the BIP78 Pay to Endpoint protocol."
repository = "https://github.com/payjoin/rust-payjoin"
readme = "../README.md"
keywords = ["bip78", "payjoin", "bitcoin"]
categories = ["api-bindings", "cryptography::cryptocurrencies", "network-programming"]
license = "MITNFA"
resolver = "2"
edition = "2021"
exclude = ["tests"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
send = []
receive = ["rand"]
base64 = ["bitcoin/base64"]
v2 = ["bitcoin/rand-std", "chacha20poly1305", "ohttp", "bhttp", "serde"]

[dependencies]
bitcoin = { version = "0.30.0", features = ["base64"] }
bip21 = "0.3.1"
chacha20poly1305 = { version = "0.10.1", optional = true }
log = { version = "0.4.14"}
ohttp = { version = "0.4.0", optional = true }
bhttp = { version = "0.4.0", optional = true }
rand = { version = "0.8.4", optional = true }
serde = { version = "1.0.186", default-features = false, optional = true }
url = "2.2.2"
serde_json = "1.0.108"

[dev-dependencies]
bitcoind = { version = "0.31.1", features = ["0_21_2"] }
env_logger = "0.9.0"
rustls = "0.21.9"
testcontainers = "0.15.0"
testcontainers-modules = { version = "0.1.3", features = ["postgres"] }
tokio = { version = "1.12.0", features = ["full"] }
ureq = "2.8.0"

[package.metadata.docs.rs]
features = ["send", "receive", "base64", "v2"]    
