name: payjoin
description: Dart bindings for payjoin (EXPERIMENTAL)
version: 0.1.0

environment:
  sdk: '^3.10.0'

dependencies:
  ffi: ^2.1.4
  hooks: any
  code_assets: any
  native_toolchain_rust: ^1.0.0
dev_dependencies:
  test: ^1.26.2
  http: ^1.4.0

hooks:
  build: hook/build.dart
