name: payjoin
description: Dart bindings for payjoin (EXPERIMENTAL)
version: 0.1.0

environment:
  sdk: "^3.10.0"

dependencies:
  ffi: ^2.1.4
  hooks: ^1.0.0
  code_assets: ^1.0.0
  native_toolchain_rust: ^1.0.0
  crypto: ^3.0.7
  ed25519_edwards: ^0.3.1
  http: ^1.6.0
  logging: ^1.3.0
  path: ^1.9.1
  toml: ^0.18.0
  yaml: ^3.1.3
  convert: ^3.1.2
dev_dependencies:
  test: ^1.26.2

hooks:
  build: hook/build.dart

executables:
  build_tool: build_tool

payjoin:
  precompiled_binaries:
    artifact_host: payjoin/rust-payjoin
    public_key: 
