name: Build and Test CSharp
on:
  pull_request:
    paths:
      - payjoin-ffi/**
env:
  RUSTUP_TOOLCHAIN: 1.85

jobs:
  build-csharp-and-test:
    name: "Build and test csharp"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: payjoin-ffi/csharp
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust 1.85.0
        uses: dtolnay/rust-toolchain@1.85.0

      - name: Use cache
        uses: Swatinem/rust-cache@v2

      - name: Install .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Generate bindings and binaries (unix)
        if: matrix.os != 'windows-latest'
        run: bash ./scripts/generate_bindings.sh

      - name: Generate bindings and binaries (windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: ./scripts/generate_bindings.ps1

      - name: Run tests
        run: dotnet test --logger "console;verbosity=minimal"
